pre-commit:
  jobs:
    - name: "lint:fmt staged"
      stage_fixed: true
      group:
        parallel: false
        jobs:
          - name: lint-staged
            run: npx eslint --fix {staged_files}
            exclude:
              - "*.sh"
              - "*.toml"
              - "*.yaml"
              - "*.yml"
              - "*.prisma"
          - name: format-staged
            run: npx prettier {staged_files} --write
            glob:
              - "*.sh"
              - "*.toml"
              - "*.prisma"
